/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as NrRouteImport } from './routes/nr'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as RnRouteImport } from './routes/rn'
import { Route as RudolfAndNoraRouteImport } from './routes/rudolf-and-nora'
import { Route as RudolfEsNoraRouteImport } from './routes/rudolf-es-nora'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProjectsDiamondRouteImport } from './routes/projects.diamond'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const NrRoute = NrRouteImport.update({
  id: '/nr',
  path: '/nr',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const RnRoute = RnRouteImport.update({
  id: '/rn',
  path: '/rn',
  getParentRoute: () => rootRouteImport,
} as any)
const RudolfAndNoraRoute = RudolfAndNoraRouteImport.update({
  id: '/rudolf-and-nora',
  path: '/rudolf-and-nora',
  getParentRoute: () => rootRouteImport,
} as any)
const RudolfEsNoraRoute = RudolfEsNoraRouteImport.update({
  id: '/rudolf-es-nora',
  path: '/rudolf-es-nora',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDiamondRoute = ProjectsDiamondRouteImport.update({
  id: '/projects/diamond',
  path: '/projects/diamond',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/nr': typeof NrRoute
  '/quotes': typeof QuotesRoute
  '/rn': typeof RnRoute
  '/rudolf-and-nora': typeof RudolfAndNoraRoute
  '/rudolf-es-nora': typeof RudolfEsNoraRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/diamond': typeof ProjectsDiamondRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/nr': typeof NrRoute
  '/quotes': typeof QuotesRoute
  '/rn': typeof RnRoute
  '/rudolf-and-nora': typeof RudolfAndNoraRoute
  '/rudolf-es-nora': typeof RudolfEsNoraRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/diamond': typeof ProjectsDiamondRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/nr': typeof NrRoute
  '/quotes': typeof QuotesRoute
  '/rn': typeof RnRoute
  '/rudolf-and-nora': typeof RudolfAndNoraRoute
  '/rudolf-es-nora': typeof RudolfEsNoraRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/diamond': typeof ProjectsDiamondRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contact'
    | '/llms.txt'
    | '/nr'
    | '/quotes'
    | '/rn'
    | '/rudolf-and-nora'
    | '/rudolf-es-nora'
    | '/sitemap.xml'
    | '/posts/$slug'
    | '/projects/$slug'
    | '/projects/diamond'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contact'
    | '/llms.txt'
    | '/nr'
    | '/quotes'
    | '/rn'
    | '/rudolf-and-nora'
    | '/rudolf-es-nora'
    | '/sitemap.xml'
    | '/posts/$slug'
    | '/projects/$slug'
    | '/projects/diamond'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contact'
    | '/llms.txt'
    | '/nr'
    | '/quotes'
    | '/rn'
    | '/rudolf-and-nora'
    | '/rudolf-es-nora'
    | '/sitemap.xml'
    | '/posts/$slug'
    | '/projects/$slug'
    | '/projects/diamond'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  NrRoute: typeof NrRoute
  QuotesRoute: typeof QuotesRoute
  RnRoute: typeof RnRoute
  RudolfAndNoraRoute: typeof RudolfAndNoraRoute
  RudolfEsNoraRoute: typeof RudolfEsNoraRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PostsSlugRoute: typeof PostsSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsDiamondRoute: typeof ProjectsDiamondRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nr': {
      id: '/nr'
      path: '/nr'
      fullPath: '/nr'
      preLoaderRoute: typeof NrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rn': {
      id: '/rn'
      path: '/rn'
      fullPath: '/rn'
      preLoaderRoute: typeof RnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rudolf-and-nora': {
      id: '/rudolf-and-nora'
      path: '/rudolf-and-nora'
      fullPath: '/rudolf-and-nora'
      preLoaderRoute: typeof RudolfAndNoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rudolf-es-nora': {
      id: '/rudolf-es-nora'
      path: '/rudolf-es-nora'
      fullPath: '/rudolf-es-nora'
      preLoaderRoute: typeof RudolfEsNoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/diamond': {
      id: '/projects/diamond'
      path: '/projects/diamond'
      fullPath: '/projects/diamond'
      preLoaderRoute: typeof ProjectsDiamondRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  NrRoute: NrRoute,
  QuotesRoute: QuotesRoute,
  RnRoute: RnRoute,
  RudolfAndNoraRoute: RudolfAndNoraRoute,
  RudolfEsNoraRoute: RudolfEsNoraRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PostsSlugRoute: PostsSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsDiamondRoute: ProjectsDiamondRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
